name: json_rpc_2
version: 3.0.1
description: >-
  Utilities to write a client or server using the JSON-RPC 2.0 spec.
homepage: https://github.com/dart-lang/json_rpc_2

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  uuid: ^3.0.5
  stack_trace: ^1.10.0
  stream_channel: ^2.1.0
  web_socket_channel:
    git: 
      url: https://github.com/hesheeat/web_socket_channel.git



dev_dependencies:
  flutter_lints: ^1.0.4
  
